#!/usr/bin/env python3
"""
03_network_calc.py 📊
=====================

Script 03 of 08 in the Networks Paper analysis pipeline.

PURPOSE:
--------
Calculate road network egress metrics for each Census Designated Place (CDP).
This is the core analysis script that quantifies how many roads (and lanes) 
cross the boundary of each community, which is critical for understanding 
evacuation capacity during wildfires.

WHAT IT CALCULATES:
-------------------
For each CDP, this script computes:
- Graph density: How interconnected the road network is
- Average node degree: Average number of roads meeting at intersections
- Boundary crossing counts: Number of roads crossing the CDP boundary by type
  (motorway, trunk, primary, secondary, tertiary)
- Lane counts: Total lanes for each road type crossing the boundary

WHY THIS MATTERS:
-----------------
Communities with few egress routes face bottlenecks during evacuations.
By counting boundary-crossing roads, we can identify which communities
have limited evacuation infrastructure and may need additional planning.

WORKFLOW:
---------
1. Load all CDP shapefiles from each state
2. For each CDP:
   a. Load the pre-computed road network graph (GraphML)
   b. Buffer the CDP boundary by specified distance (default: 500m)
   c. Clip the road network to the buffered boundary
   d. Calculate network statistics (density, degree, etc.)
   e. Count roads/lanes crossing the boundary by highway type
   f. Generate visualization plot (optional)
   g. Save boundary-crossing roads to CSV
3. Combine all results into a single output CSV
4. Process places in parallel for efficiency

DEPENDENCIES (must run first):
------------------------------
- 01_download_designated_places.ipynb (Census shapefiles)
- 02_osmnx_network_download.ipynb (GraphML road networks)

================================================================================
📥 INPUTS (Required Data Sources)
================================================================================
1. Census Place Shapefiles:
   - Location: {NETWORKS_DATA_DIR}/us-census-designated-places/
   - Format: Shapefiles (.shp) organized by state (e.g., California_06/tl_2023_06_place.shp)
   - Contains: Place boundaries, GEOID, NAME, STATE_NAME, population data
   - Source: Generated by 01_download_designated_places.ipynb

2. Road Network Graphs (GraphML):
   - Location: {NETWORKS_DATA_DIR}/output_maps/{State}_{FIPS}/{Place}_{GEOID}/
   - Format: GraphML files (e.g., Paradise_0655528.graphml)
   - Contains: OSM road network data for each place
   - Source: Generated by 02_osmnx_network_download.ipynb

================================================================================
📤 OUTPUTS (Generated Files)
================================================================================
1. Network Egress Metrics CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/network_egress_cdp/network_egress_metrics_cdp.csv
   - Contains: Network statistics per CDP (density, degree, boundary crossings by road type)

2. Visualization Maps (PNG):
   - Path: {NETWORKS_DATA_DIR}/output_maps/{State}_{FIPS}/{Place}_{GEOID}/
   - Format: {Place}_{GEOID}_visualization_{buffer}m.png
   - Contains: Road network maps with color-coded highway types and boundary crossing stats

3. Boundary Crossing Roads CSV (per place):
   - Path: {Place_Dir}/csv/boundary_crossing_roads_{buffer}m.csv
   - Contains: Individual road segments that cross the buffered boundary

4. Log File:
   - Path: <script_directory>/processing.log
   - Contains: Processing status, errors, and timing information

================================================================================
"""

import os
from pathlib import Path
import osmnx as ox
import geopandas as gpd
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar
import matplotlib.font_manager as fm
from matplotlib.patches import Patch
from shapely.geometry import (
    Polygon,
    MultiPolygon,
    MultiLineString,
    Point,
    LineString
)
import networkx as nx
import numpy as np
import traceback
from concurrent.futures import ProcessPoolExecutor, as_completed
from functools import partial
from tqdm import tqdm
import logging
import glob
import signal
import ast  # For safer evaluation of highway type strings
from datetime import datetime
import pytz

################################################################################
#                            ⏰ TIMESTAMP UTILITY                              #
################################################################################

# Timezone for timestamps (Pacific Time)
TIMEZONE = pytz.timezone('America/Los_Angeles')

def get_timestamp():
    """Return current timestamp in Pacific Time for logging."""
    return datetime.now(TIMEZONE).strftime('%Y-%m-%d %H:%M:%S %Z')

def print_timestamped(message):
    """Print a message with Pacific Time timestamp."""
    print(f"[{get_timestamp()}] {message}")

################################################################################
#                            🔧 SETTINGS                                       #
################################################################################
# These settings control the script's behavior. Modify as needed for your run.

# =============================================================================
# 🖥️ Parallel Processing Settings
# =============================================================================
NUM_CORES = 60                          # Number of parallel workers
TIMEOUT_SECONDS = 600                   # Max time per place (10 minutes)

# =============================================================================
# 📐 Analysis Parameters
# =============================================================================
BUFFER_SIZES_ANALYSIS_METERS = [500]    # Buffer distances in meters for analysis
SELECTED_STATES = []                    # Filter to specific states (empty = all states)
                                        # Example: ['California', 'Oregon']

# =============================================================================
# 🎨 Visualization Settings
# =============================================================================
CREATE_PLOTS = True                     # Generate visualization plots (True/False)
PLOT_DPI = 400                          # Plot resolution (dots per inch)
FIGURE_SIZE = (10, 10)                  # Figure size in inches
COLORED_ROAD_LW = 3                     # Line width for colored (non-residential) roads

# Road type color palette 🎨
ROAD_COLOR_PALETTE = {
    'motorway':    '#CC5A5A',           # Muted red - Major highways
    'trunk':       '#D7898D',           # Light pink - Major arterials
    'primary':     '#B6A1B7',           # Lavender - Primary roads
    'secondary':   '#8C8BAF',           # Purple-gray - Secondary roads
    'tertiary':    '#57A5D9',           # Light blue - Tertiary roads
    'residential': '#E0E0E0',           # Light gray - Local streets
}

# Major roads palette (excludes residential)
IBM_ROAD_PALETTE = {k: v for k, v in ROAD_COLOR_PALETTE.items() if k != 'residential'}

# Relevant highway types for egress analysis
RELEVANT_HIGHWAY_TYPES = ['motorway', 'trunk', 'primary', 'secondary', 'tertiary']

################################################################################
#                            📂 FILE PATHS                                     #
################################################################################
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  Configure BASE_DATA_DIR to point to your root data directory.          │
# │  You can also override it at runtime with an environment variable:      │
# │      export NETWORKS_DATA_DIR="/your/path/to/data"                      │
# │                                                                         │
# │  Expected sub-structure under BASE_DATA_DIR:                            │
# │    us-census-designated-places/   ← Census shapefiles (Step 01)        │
# │    output_maps/                   ← Road network graphs + plots (02/03) │
# │    output_csvs/                   ← All CSV outputs (Steps 03–06)       │
# └─────────────────────────────────────────────────────────────────────────┘
BASE_DATA_DIR = Path(os.environ.get(
    "NETWORKS_DATA_DIR",
    "~/data/networks_paper"           # ← change this fallback if not using env var
)).expanduser()

# =============================================================================
# 📥 INPUT PATHS
# =============================================================================
# Census-designated places shapefiles (from 01_download_designated_places.ipynb)
US_CENSUS_PLACES_DIR = BASE_DATA_DIR / 'us-census-designated-places'

# =============================================================================
# 📤 OUTPUT PATHS
# =============================================================================
# Base output directory for maps and graphs
OUTPUT_DIR = BASE_DATA_DIR / 'output_maps'

# Final CSV with network egress metrics
FINAL_CSV_DIR = BASE_DATA_DIR / 'output_csvs' / 'network_egress_cdp'
FINAL_CSV_OUTPUT = FINAL_CSV_DIR / 'network_egress_metrics_cdp.csv'

# Log file for processing status (written to the same folder as this script)
LOG_FILE = Path(__file__).parent / 'processing.log'

# =============================================================================
# 📁 Create Output Directories
# =============================================================================
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FINAL_CSV_DIR.mkdir(parents=True, exist_ok=True)

################################################################################
#                                🛠️ HELPER FUNCTIONS                          #
################################################################################
# These utility functions handle data cleaning and geometry operations needed
# for processing OSM road network data.

def sanitize_hw_type(hw_type):
    """
    Convert highway type attribute to a clean string for consistent matching.
    
    OSM highway attributes can be strings, lists, or nested structures.
    This function normalizes them to simple strings for comparison.
    
    Examples:
        "primary" -> "primary"
        ["primary", "secondary"] -> "primary_secondary"
        "['motorway']" -> "motorway"
    
    Args:
        hw_type: Highway type (string, list, or other format from OSM)
        
    Returns:
        str: Sanitized highway type string with spaces/brackets removed
    """
    hw_str = str(hw_type)
    return hw_str.replace(' ', '_') \
                 .replace('[', '') \
                 .replace(']', '') \
                 .replace(',', '') \
                 .replace("'", "")

def extract_hw_types(hw):
    """
    Given a highway attribute (string, list, nested list, etc.), return
    a flat list of individual highway-type strings.
    
    Args:
        hw: Highway type attribute (various formats)
        
    Returns:
        list: Flat list of highway type strings
    """
    types = []
    if isinstance(hw, str):
        s = hw.strip()
        if s.startswith('[') and s.endswith(']'):
            try:
                parsed = ast.literal_eval(s)
                return extract_hw_types(parsed)
            except Exception:
                types.append(s)
        else:
            types.append(s)
    elif isinstance(hw, (list, tuple)):
        for item in hw:
            types.extend(extract_hw_types(item))
    else:
        types.append(str(hw))
    return types

def get_exterior_boundary(polygon):
    """
    Extract exterior boundary from polygon geometry.
    
    Args:
        polygon: Shapely polygon or multipolygon
        
    Returns:
        Exterior boundary geometry
    """
    if isinstance(polygon, Polygon):
        return polygon.exterior
    elif isinstance(polygon, MultiPolygon):
        return MultiLineString([p.exterior for p in polygon.geoms])
    else:
        raise ValueError("Unsupported geometry type for boundary extraction.")

def timeout_handler(signum, frame):
    """Handle timeout signals during processing."""
    raise TimeoutError("Operation timed out inside worker process.")

################################################################################
#                              🔄 PROCESSING FUNCTION                         #
################################################################################
# This is the main workhorse function that processes each CDP individually.
# It runs in parallel across multiple cores for efficiency.

def process_place(place, output_dir, buffer_sizes_analysis):
    """
    Process a single Census place to compute network egress statistics.
    
    This function performs the complete analysis for one CDP:
    1. Loads the pre-computed road network graph
    2. Creates a buffered boundary around the CDP
    3. Clips the network to the buffered area
    4. Calculates network topology statistics
    5. Counts roads crossing the boundary by type
    6. Generates a visualization plot (if enabled)
    7. Saves results to CSV files
    
    The boundary crossing analysis is the key output - it tells us how many
    roads (and lanes) connect the community to the outside world, which
    directly relates to evacuation capacity.
    
    Args:
        place: GeoDataFrame row containing:
            - NAME: Place name (e.g., "Paradise")
            - GEOID: Geographic identifier (e.g., "0655528")
            - STATE_NAME: State name (e.g., "California")
            - STATEFP: State FIPS code (e.g., "06")
            - geometry: Place boundary polygon
        output_dir: Directory to save outputs (maps, CSVs)
        buffer_sizes_analysis: List of buffer distances in meters (e.g., [500])
        
    Returns:
        tuple: (stats_list, error_messages)
            - stats_list: List of dicts with network statistics per buffer size
            - error_messages: List of any error strings encountered
    """
    signal.signal(signal.SIGALRM, timeout_handler)
    signal.alarm(TIMEOUT_SECONDS)

    # Relevant highway types for analysis
    relevant_highway_types = ['motorway', 'trunk', 'primary', 'secondary', 'tertiary']
    
    # Color mapping for different highway types
    color_map = ROAD_COLOR_PALETTE.copy()

    def is_relevant_road(hw):
        """Check if highway type is relevant for analysis."""
        hw_list = extract_hw_types(hw)
        return any(sanitize_hw_type(t) in relevant_highway_types for t in hw_list)

    stats_list = []
    error_messages = []

    try:
        place_name = place['NAME']
        geoid      = place['GEOID']
        state_name = place['STATE_NAME']
        statefp    = place['STATEFP']
        polygon    = place.geometry

        # Prepare output directories
        state_dir_name = f"{state_name}_{statefp}"
        sanitized_name = "".join(c if c.isalnum() else "_" for c in place_name).strip("_")
        place_folder   = f"{sanitized_name}_{geoid}"
        place_dir      = os.path.join(output_dir, state_dir_name, place_folder)
        os.makedirs(place_dir, exist_ok=True)
        csv_dir = os.path.join(place_dir, 'csv')
        os.makedirs(csv_dir, exist_ok=True)

        # Load saved GraphML
        graph_path = os.path.join(place_dir, f"{sanitized_name}_{geoid}.graphml")
        if not os.path.exists(graph_path):
            error_messages.append(f"GraphML not found for {place_name} ({geoid}).")
            return stats_list, error_messages
        G = ox.load_graphml(graph_path)

        # Project polygon to UTM
        poly_ser = gpd.GeoSeries([polygon], crs='EPSG:4326')
        utm_crs  = poly_ser.estimate_utm_crs()
        poly_utm = poly_ser.to_crs(utm_crs)

        # Extract nodes and edges
        nodes_full, edges_full = ox.graph_to_gdfs(G)
        if edges_full is None or edges_full.empty:
            # No edges → empty stats & CSVs
            for buf in buffer_sizes_analysis:
                stats_list.append({
                    'GEOID': geoid, 'buffer_distance': buf,
                    'graph_density': np.nan,
                    'average_degree': np.nan,
                    'num_nodes': 0
                })
                pd.DataFrame(columns=['highway','geometry']).to_csv(
                    os.path.join(csv_dir, f"boundary_crossing_roads_{buf}m.csv"),
                    index=False
                )
            return stats_list, error_messages

        # Ensure edges are in EPSG:4326
        if edges_full.crs is None:
            edges_full.set_crs(epsg=4326, inplace=True)
        elif edges_full.crs.to_string() != 'EPSG:4326':
            edges_full = edges_full.to_crs(epsg=4326)

        base_data = {'GEOID': geoid}

        # Process each buffer size
        for buf in buffer_sizes_analysis:
            stats = base_data.copy()
            stats['buffer_distance'] = buf

            buf_poly_utm = poly_utm.buffer(buf)
            buf_polygon   = buf_poly_utm.to_crs('EPSG:4326').iloc[0]

            # Truncate graph to buffered polygon
            try:
                G_clip = ox.truncate.truncate_graph_polygon(
                    G, buf_polygon, retain_all=True, truncate_by_edge=True
                )
            except ValueError:
                stats.update({'graph_density':np.nan,'average_degree':np.nan,'num_nodes':0})
                stats_list.append(stats)
                pd.DataFrame(columns=edges_full.columns).to_csv(
                    os.path.join(csv_dir, f"boundary_crossing_roads_{buf}m.csv"),
                    index=False
                )
                continue

            if G_clip.number_of_nodes() == 0:
                stats.update({'graph_density':np.nan,'average_degree':np.nan,'num_nodes':0})
                stats_list.append(stats)
                pd.DataFrame(columns=edges_full.columns).to_csv(
                    os.path.join(csv_dir, f"boundary_crossing_roads_{buf}m.csv"),
                    index=False
                )
                continue

            # Compute basic network statistics
            try:
                basic = ox.basic_stats(G_clip, area=buf_polygon.area)
                stats.update(basic)
            except Exception:
                stats.update({'density':np.nan,'avg_clustering':np.nan})
            
            stats['graph_density']   = nx.density(G_clip)
            degrees = [d for _, d in G_clip.degree()]
            stats['average_degree']  = np.mean(degrees) if degrees else 0
            stats['num_nodes']       = len(G_clip.nodes)

            # Initialize boundary crossing counters
            for hw in relevant_highway_types:
                stats[f'boundary_crossing_edges_{hw}'] = 0
                stats[f'boundary_crossing_lanes_{hw}'] = 0

            # Find edges crossing boundary
            boundary_edges = edges_full[edges_full.geometry.crosses(get_exterior_boundary(buf_polygon))]
            if 'highway' in boundary_edges.columns:
                relevant = boundary_edges[boundary_edges['highway'].apply(is_relevant_road)]
            else:
                relevant = gpd.GeoDataFrame(columns=edges_full.columns)

            # Save boundary crossing roads to CSV
            relevant.to_csv(
                os.path.join(csv_dir, f"boundary_crossing_roads_{buf}m.csv"),
                index=False
            )

            # Tally edges & lanes by highway type
            for _, row in relevant.iterrows():
                hw_vals = extract_hw_types(row.get('highway'))
                lanes   = row.get('lanes', 1)
                try:
                    lane_count = int(lanes) if not pd.isna(lanes) else 1
                except:
                    lane_count = 1
                for t in hw_vals:
                    t_s = sanitize_hw_type(t)
                    if t_s in relevant_highway_types:
                        stats[f'boundary_crossing_edges_{t_s}'] += 1
                        stats[f'boundary_crossing_lanes_{t_s}'] += lane_count

            # =============================================================================
            # 📊 PLOTTING SECTION - Create visualization plots
            # =============================================================================
            if CREATE_PLOTS:
                fig, ax = plt.subplots(figsize=(10,10), dpi=PLOT_DPI)

                # Plot original CDP polygon (light blue fill)
                gpd.GeoSeries([polygon], crs='EPSG:4326').plot(
                    ax=ax, facecolor='#ccf2ff', edgecolor='none', alpha=0.5
                )

                # Plot buffered boundary
                gpd.GeoSeries([buf_polygon]).plot(
                    ax=ax,
                    facecolor='none', edgecolor='black', lw=2
                )

                # Get just the clipped edges for plotting - draw each road type in its own color
                clipped = edges_full[edges_full.index.isin(G_clip.edges())]
                if not clipped.empty:
                    # Draw residential FIRST so it sits under all other road classes
                    overlay_order = ['residential', 'tertiary', 'secondary', 'primary', 'trunk', 'motorway']
                    # Track which edges get classified so unclassified ones can be drawn in gray
                    classified_idx = set()
                    for hw_type in overlay_order:
                        col = color_map.get(hw_type)
                        if col is None:
                            continue
                        mask = clipped['highway'].apply(
                            lambda h: hw_type in extract_hw_types(h)
                        ) if 'highway' in clipped.columns else pd.Series(False, index=clipped.index)
                        subset = clipped[mask]
                        if not subset.empty:
                            classified_idx.update(subset.index.tolist())
                            lw = 2 if hw_type in ['motorway', 'trunk'] else 1.5
                            z = 1 if hw_type == 'residential' else 2
                            subset.plot(ax=ax, linewidth=lw, color=col, zorder=z)
                    # Draw any unclassified edges (e.g. service roads, unclassified) in gray
                    unclassified = clipped[~clipped.index.isin(classified_idx)]
                    if not unclassified.empty:
                        unclassified.plot(ax=ax, linewidth=1, color='gray', zorder=0)

                # Remove ticks & labels for cleaner appearance
                ax.set_xticks([])
                ax.set_yticks([])

                # Create legend with road types and boundaries
                legend_handles = [
                    Patch(facecolor='#ccf2ff', edgecolor='none', label='Original CDP'),
                    Line2D([0],[0], color='black', lw=2, label='Buffered CDP boundary'),
                    Line2D([0],[0], color='gray',  lw=2, label='Other roads'),
                    Line2D([0],[0], color=color_map['motorway'],  lw=4, label='Motorway'),
                    Line2D([0],[0], color=color_map['trunk'],     lw=4, label='Trunk'),
                    Line2D([0],[0], color=color_map['primary'],   lw=4, label='Primary'),
                    Line2D([0],[0], color=color_map['secondary'], lw=4, label='Secondary'),
                    Line2D([0],[0], color=color_map['tertiary'],  lw=4, label='Tertiary'),
                    Line2D([0],[0], color=color_map['residential'], lw=1.5, label='Residential'),
                ]
                ax.legend(handles=legend_handles, bbox_to_anchor=(1.05,1), loc='upper left')

                # Add scale bar (placed OUTSIDE the plot area, in the bottom figure margin)
                scale_len = 5 / 111.32  # 5 km in degrees (1 degree latitude ~ 111.32 km)
                sb = AnchoredSizeBar(
                    ax.transData, scale_len, "",
                    loc='lower center', pad=0.1, borderpad=0.5,
                    color='black', frameon=False, size_vertical=0.001,
                    fontproperties=fm.FontProperties(size=10),
                    bbox_to_anchor=(0.5, 0.075), bbox_transform=fig.transFigure
                )
                ax.add_artist(sb)

                # Add statistics text and title
                # Increase bottom margin to make room for outside scalebar and stats text
                plt.tight_layout(rect=[0,0.18,0.85,1])
                stats_txt = (
                    f"Boundary Crossing Roads:\n"
                    f"Motorway: {stats.get('boundary_crossing_edges_motorway',0)} roads, "
                    f"{stats.get('boundary_crossing_lanes_motorway',0)} lanes\n"
                    f"Trunk: {stats.get('boundary_crossing_edges_trunk',0)} roads, "
                    f"{stats.get('boundary_crossing_lanes_trunk',0)} lanes\n"
                    f"Primary: {stats.get('boundary_crossing_edges_primary',0)} roads, "
                    f"{stats.get('boundary_crossing_lanes_primary',0)} lanes\n"
                    f"Secondary: {stats.get('boundary_crossing_edges_secondary',0)} roads, "
                    f"{stats.get('boundary_crossing_lanes_secondary',0)} lanes\n"
                    f"Tertiary: {stats.get('boundary_crossing_edges_tertiary',0)} roads, "
                    f"{stats.get('boundary_crossing_lanes_tertiary',0)} lanes"
                )
                # Move stats box to the bottom-left so it doesn't cover the centered scale bar
                fig.text(
                    0.08, 0.02, stats_txt,
                    ha='left', va='bottom',
                    fontsize=12,
                    bbox=dict(facecolor='white', alpha=0.7)
                )
                fig.text(
                    0.5, 0.97, f"{state_name} - {place_name}",
                    ha='center', va='top',
                    fontsize=14, fontweight='bold',
                    bbox=dict(facecolor='white', alpha=0.7)
                )

                # Save the plot
                plt.savefig(
                    os.path.join(
                        place_dir,
                        f"{sanitized_name}_{geoid}_visualization_{buf}m.png"
                    ),
                    dpi=PLOT_DPI
                )
                plt.close(fig)

            stats_list.append(stats)

    except TimeoutError:
        logging.error(f"Timeout after {TIMEOUT_SECONDS}s for {place.get('NAME','Unknown')} ({place.get('GEOID','Unknown')})")
    except Exception as e:
        logging.error(f"Unexpected error for {place.get('NAME')}: {e}\n{traceback.format_exc()}")
    finally:
        signal.alarm(0)

    return stats_list, error_messages

################################################################################
#                                    🚀 MAIN LOGIC                            #
################################################################################

def main():
    """Main execution function."""
    # Setup logging
    logging.basicConfig(
        filename=LOG_FILE,
        level=logging.INFO,
        format='%(asctime)s:%(levelname)s:%(message)s'
    )

    print_timestamped("🔍 Loading Census place data...")
    
    # Find all state directories
    all_state_dirs = [d for d in glob.glob(os.path.join(US_CENSUS_PLACES_DIR,'*')) if os.path.isdir(d)]
    if not all_state_dirs:
        logging.error("No state directories found.")
        print_timestamped("❌ Error: No state directories found.")
        return

    # Load and combine all place data
    gdf_all = gpd.GeoDataFrame()
    for sd in all_state_dirs:
        base = os.path.basename(sd)
        if '_' not in base:
            continue
        name, fp = base.rsplit('_',1)
        if SELECTED_STATES and name not in SELECTED_STATES:
            continue
        for shp in glob.glob(os.path.join(sd,'*.shp')):
            try:
                gdf = gpd.read_file(shp)
                gdf = gdf.set_crs(epsg=4326, allow_override=True) if gdf.crs is None else gdf.to_crs(epsg=4326)
                gdf['STATEFP'] = fp
                gdf['STATE_NAME'] = name
                gdf_all = pd.concat([gdf_all, gdf], ignore_index=True)
            except Exception as e:
                logging.warning(f"Error reading {shp}: {e}")

    if gdf_all.empty:
        logging.error("No places to process.")
        print_timestamped("❌ Error: No places to process.")
        return

    print_timestamped(f"📊 Processing {len(gdf_all)} places using {NUM_CORES} cores...")

    # Process places in parallel
    process_fn = partial(process_place, output_dir=OUTPUT_DIR, buffer_sizes_analysis=BUFFER_SIZES_ANALYSIS_METERS)
    all_stats = []
    all_errors = []
    
    with ProcessPoolExecutor(max_workers=NUM_CORES) as executor:
        futures = {executor.submit(process_fn, row): row for _, row in gdf_all.iterrows()}
        for future in tqdm(as_completed(futures), total=len(futures), desc="🔄 Processing places"):
            try:
                stats, errs = future.result()
                all_stats.extend(stats)
                all_errors.extend(errs)
            except Exception as e:
                logging.error(f"Error in future: {e}")

    # Save results
    print_timestamped("💾 Saving results to CSV...")
    pd.DataFrame(all_stats).to_csv(FINAL_CSV_OUTPUT, index=False)
    
    if all_errors:
        print_timestamped(f"⚠️  Completed with {len(all_errors)} errors; see {LOG_FILE} for details.")
    else:
        print_timestamped("✅ All places processed successfully!")
    
    print_timestamped(f"📈 Results saved to: {FINAL_CSV_OUTPUT}")

if __name__ == "__main__":
    main()
