#!/usr/bin/env python3
"""
06_output_csv_join.py 📄
========================

Script 06 of 08 in the Networks Paper analysis pipeline.

PURPOSE:
--------
Combine all analysis outputs into a single unified dataset. This script merges
the results from network analysis, WUI classification, burn probability, and
RPS calculations into one comprehensive CSV file for statistical analysis.

WHY THIS MATTERS:
-----------------
Each previous script produces its own output CSV with different metrics.
To perform multivariate analysis (e.g., correlating egress capacity with
burn probability), we need all metrics in one dataset joined by GEOID.

WHAT IT JOINS:
--------------
1. Census attributes (population, demographics) from shapefiles
2. Network egress metrics (boundary crossings, lanes) from step 03
3. WUI land cover classification from step 04
4. Burn probability statistics from step 05
5. Risk to Potential Structures (RPS) from step 05

WORKFLOW:
---------
1. Load shapefile attributes for all CDPs
2. Load each analysis CSV (WUI, network, burn prob, RPS)
3. Normalize GEOID formats across all datasets
4. Merge all datasets on GEOID using left joins
5. Add state names from FIPS codes
6. Generate missing values report by state
7. Save combined CSV and missing values report

DEPENDENCIES (must run first):
------------------------------
- 01_download_designated_places.ipynb (Census shapefiles)
- 03_network_calc.py (network egress metrics)
- 04_wui_cdp_calculation.ipynb (WUI classification)
- 05_burn_prob_rps_calc.ipynb (burn probability and RPS)

================================================================================
📥 INPUTS (Required Data Sources)
================================================================================
1. WUI Land Cover CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/wui_land_cover_cdp/wui_land_cover_cdp.csv
   - Source: Generated by 04_wui_cdp_calculation.ipynb
   - Contains: WUI classification statistics per CDP

2. Network Egress Metrics CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/network_egress_cdp/network_egress_metrics_cdp.csv
   - Source: Generated by 03_network_calc.py
   - Contains: Road network egress statistics (boundary crossings, lanes, density)

3. Burn Probability CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/burn_prob_cdp/burn_prob_cdps_all_states.csv
   - Source: Generated by 05_burn_prob_rps_calc.ipynb
   - Contains: Burn probability zonal statistics (mean, min, max, etc.)

4. RPS (Risk to Potential Structures) CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/rps_cdp/rps_cdps_all_states.csv
   - Source: Generated by 05_burn_prob_rps_calc.ipynb
   - Contains: RPS zonal statistics per CDP

5. Census Place Shapefiles:
   - Path: {NETWORKS_DATA_DIR}/us-census-designated-places/
   - Source: Generated by 01_download_designated_places.ipynb
   - Contains: CDP boundaries and attributes

================================================================================
📤 OUTPUTS (Generated Files)
================================================================================
1. Combined CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/combined_csv/combined_data.csv
   - Contains: All CDP attributes merged on GEOID (demographics, WUI, network, burn, RPS)

2. Missing Values Report CSV:
   - Path: {NETWORKS_DATA_DIR}/output_csvs/combined_csv/missing_values_by_state.csv
   - Contains: Count of missing values per column, grouped by state

================================================================================
"""

import os
from pathlib import Path
import glob
import pandas as pd
import geopandas as gpd
from datetime import datetime
import pytz

################################################################################
#                            ⏰ TIMESTAMP UTILITY                              #
################################################################################

# Timezone for timestamps (Pacific Time)
TIMEZONE = pytz.timezone('America/Los_Angeles')

def get_timestamp():
    """Return current timestamp in Pacific Time for logging."""
    return datetime.now(TIMEZONE).strftime('%Y-%m-%d %H:%M:%S %Z')

def print_timestamped(message):
    """Print a message with Pacific Time timestamp."""
    print(f"[{get_timestamp()}] {message}")

################################################################################
#                            🔧 SETTINGS                                       #
################################################################################

# =============================================================================
# 📝 Output Settings
# =============================================================================
VERBOSE_SUMMARIES = True    # Print detailed column/missing value info (True/False)

################################################################################
#                            📂 FILE PATHS                                     #
################################################################################
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  Configure BASE_DATA_DIR to point to your root data directory.          │
# │  You can also override it at runtime with an environment variable:      │
# │      export NETWORKS_DATA_DIR="/your/path/to/data"                      │
# │                                                                         │
# │  Expected sub-structure under BASE_DATA_DIR:                            │
# │    us-census-designated-places/   ← Census shapefiles (Step 01)        │
# │    output_csvs/                   ← All CSV outputs (Steps 03–06)       │
# └─────────────────────────────────────────────────────────────────────────┘
BASE_DATA_DIR = Path(os.environ.get(
    "NETWORKS_DATA_DIR",
    "~/data/networks_paper"           # ← change this fallback if not using env var
)).expanduser()
OUTPUT_CSVS_DIR = BASE_DATA_DIR / 'output_csvs'

# =============================================================================
# 📥 INPUT PATHS
# =============================================================================
# WUI land cover statistics (from 04_wui_cdp_calculation.ipynb)
wui_csv = OUTPUT_CSVS_DIR / 'wui_land_cover_cdp' / 'wui_land_cover_cdp.csv'

# Network egress metrics (from 03_network_calc.py)
network_csv = OUTPUT_CSVS_DIR / 'network_egress_cdp' / 'network_egress_metrics_cdp.csv'

# Burn probability statistics (from 05_burn_prob_rps_calc.ipynb)
burn_csv = OUTPUT_CSVS_DIR / 'burn_prob_cdp' / 'burn_prob_cdps_all_states.csv'

# RPS statistics (from 05_burn_prob_rps_calc.ipynb)
rps_csv = OUTPUT_CSVS_DIR / 'rps_cdp' / 'rps_cdps_all_states.csv'

# Census place shapefiles root (from 01_download_designated_places.ipynb)
shp_root = BASE_DATA_DIR / 'us-census-designated-places'

# =============================================================================
# 📤 OUTPUT PATHS
# =============================================================================
# Combined CSV output directory
output_dir = OUTPUT_CSVS_DIR / 'combined_csv'

# Final combined CSV
output_csv = output_dir / 'combined_data.csv'

# Missing values report CSV
missing_output_csv = output_dir / 'missing_values_by_state.csv'

# Create output directories
output_dir.mkdir(parents=True, exist_ok=True)

################################################################################
#                            🗺️ FIPS CODE MAPPINGS                            #
################################################################################

# State FIPS code to state name mapping
FIPS_TO_STATE = {
    '01': 'Alabama', '02': 'Alaska', '04': 'Arizona', '05': 'Arkansas',
    '06': 'California', '08': 'Colorado', '09': 'Connecticut', '10': 'Delaware',
    '11': 'District of Columbia', '12': 'Florida', '13': 'Georgia', '15': 'Hawaii',
    '16': 'Idaho', '17': 'Illinois', '18': 'Indiana', '19': 'Iowa', '20': 'Kansas',
    '21': 'Kentucky', '22': 'Louisiana', '23': 'Maine', '24': 'Maryland',
    '25': 'Massachusetts', '26': 'Michigan', '27': 'Minnesota', '28': 'Mississippi',
    '29': 'Missouri', '30': 'Montana', '31': 'Nebraska', '32': 'Nevada',
    '33': 'New Hampshire', '34': 'New Jersey', '35': 'New Mexico', '36': 'New York',
    '37': 'North Carolina', '38': 'North Dakota', '39': 'Ohio', '40': 'Oklahoma',
    '41': 'Oregon', '42': 'Pennsylvania', '44': 'Rhode Island', '45': 'South Carolina',
    '46': 'South Dakota', '47': 'Tennessee', '48': 'Texas', '49': 'Utah',
    '50': 'Vermont', '51': 'Virginia', '53': 'Washington', '54': 'West Virginia',
    '55': 'Wisconsin', '56': 'Wyoming'
}

################################################################################
#                              🧠 CORE FUNCTIONS                               #
################################################################################

def load_shapefile_attributes(shp_root_dir: str) -> pd.DataFrame:
    """Load all place shapefiles and return attributes-only DataFrame.

    Returns an empty DataFrame if no shapefiles can be read.
    """
    shp_files = glob.glob(os.path.join(shp_root_dir, "*", "*.shp"))
    gdfs = []

    print("Loading shapefiles...")
    for shp in shp_files:
        try:
            gdf = gpd.read_file(shp)
            print(f"  Loaded shapefile: {shp} (polygons: {len(gdf)})")
            gdfs.append(gdf)
        except Exception as e:
            print(f"  Error reading {shp}: {e}")

    if not gdfs:
        print("No shapefiles were loaded; creating an empty DataFrame.")
        return pd.DataFrame()

    shp_concat = pd.concat(gdfs, ignore_index=True)
    print(f"\nTotal shapefile records after concatenation: {len(shp_concat)}")
    # Drop geometry to work with attributes only
    return shp_concat.drop(columns="geometry")


def read_csv_ensure_geoid(path: str) -> pd.DataFrame:
    """Read CSV and ensure GEOID column is string if present."""
    df = pd.read_csv(path)
    if "GEOID" in df.columns:
        df["GEOID"] = df["GEOID"].astype(str)
    return df


def determine_expected_geoid_length(shp_df: pd.DataFrame) -> int:
    """Infer expected GEOID length from shapefile attributes, default to 5."""
    if "GEOID" in shp_df.columns and not shp_df.empty:
        expected_length = shp_df["GEOID"].str.len().mode()[0]
        print(f"\nExpected GEOID length determined from shapefile: {expected_length}")
        return int(expected_length)
    print("\nShapefile GEOID not available; defaulting expected length to 5")
    return 5


def zfill_geoid(df: pd.DataFrame, length: int) -> pd.DataFrame:
    """Pad GEOID with leading zeros to a specific length if present."""
    if "GEOID" in df.columns:
        df["GEOID"] = df["GEOID"].astype(str).str.zfill(length)
    return df


################################################################################
#                               🚀 MAIN WORKFLOW                               #
################################################################################

def main():
    # -------------------------------
    # Step 1: Load shapefile attributes
    # -------------------------------
    shp_df = load_shapefile_attributes(shp_root)
    if "GEOID" in shp_df.columns:
        shp_df["GEOID"] = shp_df["GEOID"].astype(str)

    # -------------------------------
    # Step 2: Load CSVs
    # -------------------------------
    print("\nLoading CSV files...")
    wui_df = read_csv_ensure_geoid(wui_csv)
    print(f"  Loaded WUI CSV with {len(wui_df)} records.")
    network_df = read_csv_ensure_geoid(network_csv)
    print(f"  Loaded network CSV with {len(network_df)} records.")
    burn_df = read_csv_ensure_geoid(burn_csv)
    print(f"  Loaded burn probability CSV with {len(burn_df)} records.")
    rps_df = read_csv_ensure_geoid(rps_csv)
    print(f"  Loaded RPS CSV with {len(rps_df)} records.")

    # -------------------------------
    # Step 3: Normalize GEOID widths
    # -------------------------------
    expected_length = determine_expected_geoid_length(shp_df)
    shp_df = zfill_geoid(shp_df, expected_length)
    for df in [wui_df, network_df, burn_df, rps_df]:
        zfill_geoid(df, expected_length)

    # -------------------------------
    # Optional: dataset summaries
    # -------------------------------
    if VERBOSE_SUMMARIES:
        print("\n--- Individual Dataset Columns and Missing Values ---")
        print("\nWUI CSV Columns:")
        print(wui_df.columns.tolist())
        print("Missing values in WUI CSV:")
        print(wui_df.isnull().sum())

        print("\nNetwork CSV Columns:")
        print(network_df.columns.tolist())
        print("Missing values in Network CSV:")
        print(network_df.isnull().sum())

        print("\nBurn Probability CSV Columns:")
        print(burn_df.columns.tolist())
        print("Missing values in Burn Probability CSV:")
        print(burn_df.isnull().sum())

        print("\nRPS CSV Columns:")
        print(rps_df.columns.tolist())
        print("Missing values in RPS CSV:")
        print(rps_df.isnull().sum())

        if not shp_df.empty:
            print("\nShapefile Attributes Columns:")
            print(shp_df.columns.tolist())
            print("Missing values in Shapefile Attributes:")
            print(shp_df.isnull().sum())

    # -------------------------------
    # Step 4: Merge datasets on GEOID
    # -------------------------------
    if not shp_df.empty:
        combined_df = shp_df.merge(wui_df, on="GEOID", how="left")
    else:
        print("No shapefiles available. Using WUI CSV as base.")
        combined_df = wui_df.copy()

    combined_df = combined_df.merge(network_df, on="GEOID", how="left")
    combined_df = combined_df.merge(burn_df, on="GEOID", how="left")
    combined_df = combined_df.merge(rps_df, on="GEOID", how="left")

    print(f"\nCombined dataframe has {len(combined_df)} records and {len(combined_df.columns)} columns.")
    print("\nFinal Combined CSV Columns:")
    print(combined_df.columns.tolist())
    print("\nMissing values in Final Combined CSV:")
    print(combined_df.isnull().sum())

    # -------------------------------
    # Step 5: Add state name from FIPS and compute missing by state
    # -------------------------------
    # Using FIPS_TO_STATE mapping from config.py

    if 'State FIPS' in combined_df.columns:
        combined_df['State FIPS'] = combined_df['State FIPS'].astype(str).str.zfill(2)
    else:
        print("\nWarning: 'State FIPS' column not found in the combined dataframe.")

    combined_df['state_name'] = combined_df['State FIPS'].map(FIPS_TO_STATE)

    missing_data = []
    for col in combined_df.columns:
        if col == "state_name":
            continue
        # Group by state_name and count missing entries
        missing_counts = combined_df.groupby("state_name")[col].apply(lambda x: x.isnull().sum())
        for state, count in missing_counts.items():
            if count > 0:
                missing_data.append({'state_name': state, 'column': col, 'missing_count': count})

    missing_df = pd.DataFrame(missing_data)
    missing_df = missing_df.sort_values(["state_name", "column"]).reset_index(drop=True)
    print("\nMissing values by state and column:")
    print(missing_df)

    # -------------------------------
    # Step 6: Save outputs
    # -------------------------------
    combined_df.to_csv(output_csv, index=False)
    print(f"\nCombined CSV saved to: {output_csv}")

    missing_df.to_csv(missing_output_csv, index=False)
    print(f"Missing values DataFrame saved to: {missing_output_csv}")


if __name__ == "__main__":
    main()


