#!/usr/bin/env python3
"""
network_plot.py 🎨
==================

Utility script for generating network visualization maps.

PURPOSE:
--------
Create publication-quality maps showing road networks for Census Designated
Places (CDPs). This is a standalone utility that can be used independently
or called from other scripts (like 03_network_calc.py).

VISUALIZATION FEATURES:
-----------------------
- CDP boundary shown as light blue filled polygon
- Buffered boundary shown as black outline
- Roads color-coded by highway type:
  * Motorway (pink) - Major highways/interstates
  * Trunk (orange) - Major arterials
  * Primary (yellow) - Primary roads
  * Secondary (blue) - Secondary roads
  * Tertiary (purple) - Tertiary roads
  * Residential (gray) - Local streets
- Legend showing road types and statistics
- Boundary crossing counts displayed on plot

HOW COLORS WERE CHOSEN:
-----------------------
The color palette uses IBM Design's colorblind-friendly colors to ensure
accessibility. Road importance is indicated by color warmth (motorways are
warm pink, minor roads are cooler blue/purple).

USAGE:
------
This script can be:
1. Run standalone: python network_plot.py
2. Imported and called: from network_plot import create_network_visualization

DEPENDENCIES:
-------------
- Road network graphs (GraphML) from 02_osmnx_network_download.ipynb
- Place geometries from Census shapefiles

================================================================================
📥 INPUTS (Required Data Sources)
================================================================================
1. Road Network Graphs (GraphML):
   - Path: {NETWORKS_DATA_DIR}/output_maps/{State}_{FIPS}/{Place}_{GEOID}/
   - Format: GraphML files (e.g., Paradise_0655528.graphml)
   - Source: Generated by 02_osmnx_network_download.ipynb

2. Census Place Shapefiles (for standalone plotting):
   - Path: {NETWORKS_DATA_DIR}/us-census-designated-places/
   - Format: Shapefiles with place boundary geometries

3. Network Egress CSV (optional, for CSV-based plotting):
   - Path: {NETWORKS_DATA_DIR}/output_csvs/network_egress_cdp/network_egress_metrics_cdp.csv
   - Contains: Network statistics per CDP

================================================================================
📤 OUTPUTS (Generated Files)
================================================================================
1. Network Visualization Maps (PNG):
   - Path: {NETWORKS_DATA_DIR}/output_maps/{State}_{FIPS}/{Place}_{GEOID}/
   - Format: {Place}_{GEOID}_visualization_{buffer}m.png
   - Contains: Color-coded road network maps with legends and statistics

2. Log File:
   - Path: <script_directory>/processing.log
   - Contains: Processing status and error messages

================================================================================
"""

import os
from pathlib import Path
import osmnx as ox
import geopandas as gpd
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
from shapely.geometry import (
    Polygon,
    MultiPolygon,
    MultiLineString,
    Point,
    LineString
)
from matplotlib.lines import Line2D
import networkx as nx
import numpy as np
import traceback
import signal
import ast  # For safer evaluation of highway type strings
from mpl_toolkits.axes_grid1.anchored_artists import AnchoredSizeBar
import matplotlib.font_manager as fm
from matplotlib.patches import Patch

################################################################################
#                            ⏰ TIMESTAMP UTILITY                              #
################################################################################

from datetime import datetime
import pytz

# Timezone for timestamps (Pacific Time)
TIMEZONE = pytz.timezone('America/Los_Angeles')

def get_timestamp():
    """Return current timestamp in Pacific Time for logging."""
    return datetime.now(TIMEZONE).strftime('%Y-%m-%d %H:%M:%S %Z')

def print_timestamped(message):
    """Print a message with Pacific Time timestamp."""
    print(f"[{get_timestamp()}] {message}")

################################################################################
#                            🔧 SETTINGS                                       #
################################################################################

# =============================================================================
# 🖥️ Processing Settings
# =============================================================================
TIMEOUT_SECONDS = 600                   # Max processing time per place (seconds)

# =============================================================================
# 🎨 Visualization Settings
# =============================================================================
PLOT_DPI = 400                          # Plot resolution (dots per inch)
FIGURE_SIZE = (10, 10)                  # Figure dimensions (width, height) in inches

# IBM Design colorblind-friendly color palette for road types 🎨
HIGHWAY_COLOR_MAP = {
    'motorway':    '#d12771',           # Magenta 50 (pink) - Major highways
    'trunk':       '#ff832b',           # Orange 40 - Major arterials
    'primary':     '#f1c21b',           # Yellow 30 - Primary roads
    'secondary':   '#0f62fe',           # Blue 60 - Secondary roads
    'tertiary':    '#6929c4',           # Purple 60 - Tertiary roads
    'residential': '#eeeeee',           # Light gray - Local streets
}

# Relevant highway types for egress analysis (in priority order)
RELEVANT_HIGHWAY_TYPES = ['motorway', 'trunk', 'primary', 'secondary', 'tertiary']

################################################################################
#                            📂 FILE PATHS                                     #
################################################################################
# ┌─────────────────────────────────────────────────────────────────────────┐
# │  Configure BASE_DATA_DIR to point to your root data directory.          │
# │  You can also override it at runtime with an environment variable:      │
# │      export NETWORKS_DATA_DIR="/your/path/to/data"                      │
# │  Or edit the default path below.                                        │
# └─────────────────────────────────────────────────────────────────────────┘
BASE_DATA_DIR = Path(os.environ.get(
    "NETWORKS_DATA_DIR",
    "~/data/networks_paper"           # ← change this fallback if not using env var
)).expanduser()

# =============================================================================
# 📤 OUTPUT PATHS
# =============================================================================
OUTPUT_DIR = BASE_DATA_DIR / 'output_maps'                  # Visualization output directory
LOG_FILE = Path(__file__).parent / 'processing.log'         # Processing log file

################################################################################
#                                🛠️ HELPER FUNCTIONS                          #
################################################################################

def sanitize_hw_type(hw_type):
    """
    Convert any type to string and strip unwanted characters.
    
    Args:
        hw_type: Highway type (string, list, or other)
        
    Returns:
        str: Sanitized highway type string
    """
    hw_str = str(hw_type)
    return hw_str.replace(' ', '_') \
                 .replace('[', '') \
                 .replace(']', '') \
                 .replace(',', '') \
                 .replace("'", "")

def extract_hw_types(hw):
    """
    Given a highway attribute (string, list, nested list, etc.), return
    a flat list of individual highway-type strings.
    
    Args:
        hw: Highway type attribute (various formats)
        
    Returns:
        list: Flat list of highway type strings
    """
    types = []
    if isinstance(hw, str):
        s = hw.strip()
        if s.startswith('[') and s.endswith(']'):
            try:
                parsed = ast.literal_eval(s)
                return extract_hw_types(parsed)
            except Exception:
                types.append(s)
        else:
            types.append(s)
    elif isinstance(hw, (list, tuple)):
        for item in hw:
            types.extend(extract_hw_types(item))
    else:
        types.append(str(hw))
    return types

def get_exterior_boundary(polygon):
    """
    Extract exterior boundary from polygon geometry.
    
    Args:
        polygon: Shapely polygon or multipolygon
        
    Returns:
        Exterior boundary geometry
    """
    if isinstance(polygon, Polygon):
        return polygon.exterior
    elif isinstance(polygon, MultiPolygon):
        return MultiLineString([p.exterior for p in polygon.geoms])
    else:
        raise ValueError("Unsupported geometry type for boundary extraction.")

def timeout_handler(signum, frame):
    """Handle timeout signals during processing."""
    raise TimeoutError("Operation timed out inside worker process.")

################################################################################
#                              🎨 PLOTTING FUNCTIONS                          #
################################################################################

def create_network_visualization(place, output_dir, buffer_distance=500):
    """
    Create a visualization plot for a single place's network analysis.
    
    Args:
        place: GeoDataFrame row containing place information
        output_dir: Directory to save outputs
        buffer_distance: Buffer distance in meters
        
    Returns:
        tuple: (success, error_message)
    """
    signal.signal(signal.SIGALRM, timeout_handler)
    signal.alarm(TIMEOUT_SECONDS)

    def is_relevant_road(hw):
        """Check if highway type is relevant for analysis."""
        hw_list = extract_hw_types(hw)
        return any(sanitize_hw_type(t) in RELEVANT_HIGHWAY_TYPES for t in hw_list)

    try:
        place_name = place['NAME']
        geoid      = place['GEOID']
        state_name = place['STATE_NAME']
        statefp    = place['STATEFP']
        polygon    = place.geometry

        # Prepare output directories
        state_dir_name = f"{state_name}_{statefp}"
        sanitized_name = "".join(c if c.isalnum() else "_" for c in place_name).strip("_")
        place_folder   = f"{sanitized_name}_{geoid}"
        place_dir      = os.path.join(output_dir, state_dir_name, place_folder)
        os.makedirs(place_dir, exist_ok=True)

        # Load saved GraphML
        graph_path = os.path.join(place_dir, f"{sanitized_name}_{geoid}.graphml")
        if not os.path.exists(graph_path):
            return False, f"GraphML not found for {place_name} ({geoid})."
        
        G = ox.load_graphml(graph_path)

        # Project polygon to UTM
        poly_ser = gpd.GeoSeries([polygon], crs='EPSG:4326')
        utm_crs  = poly_ser.estimate_utm_crs()
        poly_utm = poly_ser.to_crs(utm_crs)

        # Extract nodes and edges
        nodes_full, edges_full = ox.graph_to_gdfs(G)
        if edges_full is None or edges_full.empty:
            return False, f"No edges found for {place_name} ({geoid})."

        # Ensure edges are in EPSG:4326
        if edges_full.crs is None:
            edges_full.set_crs(epsg=4326, inplace=True)
        elif edges_full.crs.to_string() != 'EPSG:4326':
            edges_full = edges_full.to_crs(epsg=4326)

        # Create buffered polygon
        buf_poly_utm = poly_utm.buffer(buffer_distance)
        buf_polygon   = buf_poly_utm.to_crs('EPSG:4326').iloc[0]

        # Truncate graph to buffered polygon
        try:
            G_clip = ox.truncate.truncate_graph_polygon(
                G, buf_polygon, retain_all=True, truncate_by_edge=True
            )
        except ValueError:
            return False, f"Failed to truncate graph for {place_name} ({geoid})."

        if G_clip.number_of_nodes() == 0:
            return False, f"No nodes in clipped graph for {place_name} ({geoid})."

        # Initialize boundary crossing counters
        boundary_stats = {}
        for hw in RELEVANT_HIGHWAY_TYPES:
            boundary_stats[f'boundary_crossing_edges_{hw}'] = 0
            boundary_stats[f'boundary_crossing_lanes_{hw}'] = 0

        # Find edges crossing boundary
        boundary_edges = edges_full[edges_full.geometry.crosses(get_exterior_boundary(buf_polygon))]
        if 'highway' in boundary_edges.columns:
            relevant = boundary_edges[boundary_edges['highway'].apply(is_relevant_road)]
        else:
            relevant = gpd.GeoDataFrame(columns=edges_full.columns)

        # Tally edges & lanes by highway type
        for _, row in relevant.iterrows():
            hw_vals = extract_hw_types(row.get('highway'))
            lanes   = row.get('lanes', 1)
            try:
                lane_count = int(lanes) if not pd.isna(lanes) else 1
            except:
                lane_count = 1
            for t in hw_vals:
                t_s = sanitize_hw_type(t)
                if t_s in RELEVANT_HIGHWAY_TYPES:
                    boundary_stats[f'boundary_crossing_edges_{t_s}'] += 1
                    boundary_stats[f'boundary_crossing_lanes_{t_s}'] += lane_count

        # Create the plot
        fig, ax = plt.subplots(figsize=FIGURE_SIZE, dpi=PLOT_DPI)

        # Plot original CDP boundary
        gpd.GeoSeries([polygon]).plot(
            ax=ax,
            facecolor='#ccf2ff', edgecolor='none', alpha=0.5
        )

        # Plot buffered boundary
        gpd.GeoSeries([buf_polygon]).plot(
            ax=ax,
            facecolor='none', edgecolor='black', lw=2
        )

        # Get clipped edges for plotting
        clipped = edges_full[edges_full.index.isin(G_clip.edges())]

        # Plot each highway class in its color with unified width
        for hw_type, col in HIGHWAY_COLOR_MAP.items():
            if 'highway' in clipped.columns:
                mask = clipped['highway'].apply(lambda h: hw_type in extract_hw_types(h))
                subset = clipped[mask]
                if not subset.empty:
                    lw = 4.5 if hw_type != 'residential' else 1
                    subset.plot(ax=ax, linewidth=lw, color=col)

        # Remove ticks & labels
        ax.set_xticks([])
        ax.set_yticks([])

        # Create legend
        legend_handles = [
            Patch(facecolor='#ccf2ff', edgecolor='none', label='Original CDP'),
            Line2D([0],[0], color='black', lw=4, label='Buffered CDP'),
            Line2D([0],[0], color="#D14E4E", lw=4.5, label='Motorway'),
            Line2D([0],[0], color="#D29292", lw=4.5, label='Trunk'),
            Line2D([0],[0], color="#A68DB8", lw=4.5, label='Primary'),
            Line2D([0],[0], color="#7E7BC0", lw=4.5, label='Secondary'),
            Line2D([0],[0], color="#4A97DB", lw=4.5, label='Tertiary'),
            Line2D([0],[0], color="#BFBFBF", lw=4, label='Residential')
        ]
        ax.legend(handles=legend_handles, bbox_to_anchor=(1.05,1), loc='upper left')

        # Add scale bar
        scale_len = 5 / 111.32  # 5 km in degrees (1 degree latitude ~ 111.32 km)
        sb = AnchoredSizeBar(
            ax.transData, scale_len, "",
            loc='lower right', pad=0.1, borderpad=0.5,
            color='black', frameon=False, size_vertical=0.001,
            fontproperties=fm.FontProperties(size=10),
            bbox_to_anchor=(0.95,0.05), bbox_transform=ax.transAxes
        )
        ax.add_artist(sb)

        # Add statistics text
        plt.tight_layout(rect=[0,0.1,0.85,1])
        stats_txt = (
            f"Boundary Crossing Roads:\n"
            f"Motorway: {boundary_stats.get('boundary_crossing_edges_motorway',0)} roads, "
            f"{boundary_stats.get('boundary_crossing_lanes_motorway',0)} lanes\n"
            f"Trunk: {boundary_stats.get('boundary_crossing_edges_trunk',0)} roads, "
            f"{boundary_stats.get('boundary_crossing_lanes_trunk',0)} lanes\n"
            f"Primary: {boundary_stats.get('boundary_crossing_edges_primary',0)} roads, "
            f"{boundary_stats.get('boundary_crossing_lanes_primary',0)} lanes\n"
            f"Secondary: {boundary_stats.get('boundary_crossing_edges_secondary',0)} roads, "
            f"{boundary_stats.get('boundary_crossing_lanes_secondary',0)} lanes\n"
            f"Tertiary: {boundary_stats.get('boundary_crossing_edges_tertiary',0)} roads, "
            f"{boundary_stats.get('boundary_crossing_lanes_tertiary',0)} lanes"
        )
        fig.text(
            0.5, 0.03, stats_txt,
            ha='center', va='bottom',
            fontsize=12,
            bbox=dict(facecolor='white', alpha=0.7)
        )
        
        # Add title
        fig.text(
            0.5, 0.97, f"{state_name} - {place_name}",
            ha='center', va='top',
            fontsize=14, fontweight='bold',
            bbox=dict(facecolor='white', alpha=0.7)
        )

        # Save the plot
        output_path = os.path.join(
            place_dir,
            f"{sanitized_name}_{geoid}_visualization_{buffer_distance}m.png"
        )
        plt.savefig(output_path, dpi=PLOT_DPI)
        plt.close(fig)

        return True, f"Plot saved to {output_path}"

    except TimeoutError:
        return False, f"Timeout after {TIMEOUT_SECONDS}s for {place.get('NAME','Unknown')} ({place.get('GEOID','Unknown')})"
    except Exception as e:
        return False, f"Unexpected error for {place.get('NAME')}: {e}\n{traceback.format_exc()}"
    finally:
        signal.alarm(0)

def plot_network_from_csv(csv_path, output_dir, buffer_distance=500):
    """
    Create plots for places based on existing CSV results.
    
    Args:
        csv_path: Path to CSV file with network statistics
        output_dir: Directory to save outputs
        buffer_distance: Buffer distance in meters
        
    Returns:
        dict: Summary of plotting results
    """
    import logging
    
    # Setup logging
    logging.basicConfig(
        filename=LOG_FILE,
        level=logging.INFO,
        format='%(asctime)s:%(levelname)s:%(message)s'
    )
    
    print("🎨 Starting network visualization generation...")
    
    # Load CSV results
    try:
        df = pd.read_csv(csv_path)
        print(f"📊 Loaded {len(df)} records from {csv_path}")
    except Exception as e:
        print(f"❌ Error loading CSV: {e}")
        return {"error": str(e)}
    
    # Get unique places
    places = df[df['buffer_distance'] == buffer_distance]['GEOID'].unique()
    print(f"🔄 Generating plots for {len(places)} places...")
    
    results = {
        "successful": 0,
        "failed": 0,
        "errors": []
    }
    
    # Process each place
    for geoid in places:
        try:
            # Find the place data (this would need to be loaded from the original shapefiles)
            # For now, we'll create a mock place object
            place_data = df[df['GEOID'] == geoid].iloc[0]
            
            # Create a mock place object (in practice, you'd load this from shapefiles)
            place = {
                'NAME': f"Place_{geoid}",  # This would come from shapefile
                'GEOID': geoid,
                'STATE_NAME': "Unknown",    # This would come from shapefile
                'STATEFP': "00",           # This would come from shapefile
                'geometry': None           # This would come from shapefile
            }
            
            success, message = create_network_visualization(place, output_dir, buffer_distance)
            
            if success:
                results["successful"] += 1
                print(f"✅ {geoid}: {message}")
            else:
                results["failed"] += 1
                results["errors"].append(f"{geoid}: {message}")
                print(f"❌ {geoid}: {message}")
                
        except Exception as e:
            results["failed"] += 1
            results["errors"].append(f"{geoid}: {str(e)}")
            print(f"❌ {geoid}: Error - {str(e)}")
    
    print(f"🎨 Plotting complete! ✅ {results['successful']} successful, ❌ {results['failed']} failed")
    return results

################################################################################
#                                    🚀 MAIN LOGIC                            #
################################################################################

def main():
    """Main execution function for standalone plotting."""
    print("🎨 Network Plotting Script")
    print("=" * 50)
    print("This script generates visualization plots for network analysis.")
    print("Make sure you have run the network calculation script first!")
    print()
    
    # Example usage - you would typically call this from the calculation script
    # or provide specific parameters here
    csv_path = BASE_DATA_DIR / 'output_csvs' / 'network_egress_cdp' / 'network_egress_metrics_cdp.csv'
    
    if os.path.exists(csv_path):
        print(f"📊 Found CSV file: {csv_path}")
        results = plot_network_from_csv(csv_path, OUTPUT_DIR)
        print(f"📈 Results: {results}")
    else:
        print(f"❌ CSV file not found: {csv_path}")
        print("Please run the network calculation script first.")

if __name__ == "__main__":
    main()
